version: '3'
services:
  dev:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-dev
    env_file:
      - ./dockerfiles/.env.dev
    working_dir: /app
    volumes:
      - .:/app
      - cargo:/cargo
    ports:
      - 8888:8888
    tty: true
    stdin_open: true
volumes:
  cargo:
